// List of DEFCON nations for use in both client and server code
// Each entry: { name, code (ISO 3166-1 alpha-3), flag (emoji) }
export const DEFCON_NATIONS = [
  { name: "Algeria", code: "DZA", flag: "🇩🇿" },
  { name: "Argentina", code: "ARG", flag: "🇦🇷" },
  { name: "Australia", code: "AUS", flag: "🇦🇺" },
  { name: "Brazil", code: "BRA", flag: "🇧🇷" },
  { name: "Canada", code: "CAN", flag: "🇨🇦" },
  { name: "China", code: "CHN", flag: "🇨🇳" },
  { name: "DR Congo", code: "COD", flag: "🇨🇩" },
  { name: "Egypt", code: "EGY", flag: "🇪🇬" },
  { name: "Ethiopia", code: "ETH", flag: "🇪🇹" },
  { name: "European Union", code: "EUR", flag: "🇪🇺" },
  { name: "France", code: "FRA", flag: "🇫🇷" },
  { name: "Germany", code: "DEU", flag: "🇩🇪" },
  { name: "India", code: "IND", flag: "🇮🇳" },
  { name: "Indonesia", code: "IDN", flag: "🇮🇩" },
  { name: "Iran", code: "IRN", flag: "🇮🇷" },
  { name: "Japan", code: "JPN", flag: "🇯🇵" },
  { name: "Mexico", code: "MEX", flag: "🇲🇽" },
  { name: "NATO", code: "NAT", flag: "🇫🇲" },
  { name: "Nigeria", code: "NGA", flag: "🇳🇬" },
  { name: "Pakistan", code: "PAK", flag: "🇵🇰" },
  { name: "Poland", code: "POL", flag: "🇵🇱" },
  { name: "Russia", code: "RUS", flag: "🇷🇺" },
  { name: "Saudi Arabia", code: "SAU", flag: "🇸🇦" },
  { name: "South Africa", code: "ZAF", flag: "🇿🇦" },
  { name: "South Korea", code: "KOR", flag: "🇰🇷" },
  { name: "Turkey", code: "TUR", flag: "🇹🇷" },
  { name: "United Kingdom", code: "GBR", flag: "🇬🇧" },
  { name: "United Nations", code: "UNO", flag: "🇺🇳" },
  { name: "United States", code: "USA", flag: "🇺🇸" },
  { name: "Venezuela", code: "VEN", flag: "🇻🇪" },

  { name: "Klingon Empire", code: "KLI", flag: "🚩" },
  { name: "Pirates", code: "PIR", flag: "🏴‍☠️" },
  { name: "The Olympics", code: "OLY", flag: "🏳️" },
  { name: "LGBTQIA", code: "LGB", flag: "🏳️‍🌈" },
  { name: "Vatican City", code: "VAT", flag: "🇻🇦" },
];
